# URL correta para conexão externa (a que termina em .com)
spring.datasource.url=jdbc:postgresql://dpg-d8osnetckfvc739pghug-a.oregon-postgres.render.com:5432/chessvault_db
# Credenciais
spring.datasource.username=chessvault_db_user
spring.datasource.password=Upo6yZALWodfHlONwyyKSvFLgwAbYM0G

# Configurações de Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect