spring.application.name=ChessVault

# O Render vai injetar esses valores pelas Variáveis de Ambiente
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Configurações de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Dica: O Hibernate já detecta o banco pelo driver, não precisa do dialect